import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD FOR SAVE-JE OBSIDIAN PLUGIN.
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
  ],
  alias: {
    path: "path-browserify",
    stream: "stream-browserify",
    process: "process/browser",
  },
  inject: ["./esbuild.inject.mjs"],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  outfile: "main.js",
  define: {
    "process.env.NODE_DEBUG": "undefined",
    "process.env.DEBUG": "undefined",
    global: "window",
  },
});

if (process.argv.includes("--watch")) {
  await context.watch();
  console.log("Watching for changes...");
} else {
  await context.rebuild();
  await context.dispose();
  console.log("Build complete: main.js created.");
}
